### ISSUE TITLE
Could not link name with server: java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#27]
### Platform Information
```
22:07:57 [INFO] SubServers > These are the platforms and versions that are running SubServers.Bungee:
22:07:57 [INFO]   Linux 3.16.0-4-amd64 [x64],
22:07:57 [INFO]   Java 1.8.0_171 [x64],
22:07:57 [INFO]   HexaCord git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222,
22:07:57 [INFO]   SubServers.Bungee v2.13.2b (18w49a)
22:07:57 [INFO]
22:07:57 [INFO] You are on the latest version.
```

### What Happened
Log BungeeCord:
```
22:06:40 [INFO] SubData > /127.0.0.1:43969 has connected
22:06:41 [INFO] SubData > /127.0.0.1:43969 logged in
22:06:42 [SEVERE] java.lang.NullPointerException
22:06:42 [SEVERE]     at net.ME1312.SubServers.Bungee.Network.Packet.PacketLinkServer.execute(PacketLinkServer.java:63)
22:06:42 [SEVERE]     at net.ME1312.SubServers.Bungee.Network.Client.lambda$loop$0(Client.java:91)
22:06:42 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
22:06:42 [INFO] SubData > /127.0.0.1:43962 has disconnected

```
Log Minecraft:
```
[22:06:35] [Server thread/INFO]: [SubServers-Client-Bukkit] Loading SubServers-Client-Bukkit v2.13.2a
[22:06:40] [Server thread/INFO]: [SubServers-Client-Bukkit] Enabling SubServers-Client-Bukkit v2.13.2a
[22:06:40] [Server thread/INFO]: SubServers > Loading SubServers.Client.Bukkit v2.13.2a Libraries (for Minecraft 1.12.2)
[22:06:45] [Server thread/INFO]: SubData > Could not link name with server: java.lang.NullPointerException: null
[22:06:45] [Server thread/INFO]: SubServers > The SubData Connection was closed
```

Config BungeeCord:
```
connection_throttle: 0
custom_server_name: RageBears - Minecraft
online_mode: true
groups:
  md_5:
  - default
servers:
  lobby:
    motd: ''
    address: localhost:25565
    restricted: false
always_handle_packets: false
ip_forward: true
forge_support: false
player_limit: -1
disabled_commands:
- disabledcommandhere
log_pings: true
log_commands: false
stats: --
listeners:
- query_port: 25577
  motd: ''
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: true
  host: 0.0.0.0:25565
  forced_hosts:
    mine.ragebears.de: lobby
  max_players: 200
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
  proxy_protocol: false
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.list
prevent_proxy_connections: false
timeout: 30000
```
SubServer-Bungee Config:
```
Settings:
  Version: '2.11.2a+'
  Log-Creator: true
  Override-Bungee-Commands: true
  UPnP:
    Forward-Proxy: false
    Forward-SubData: false
    Forward-Servers: false
  SubData:
    Address: '127.0.0.1:4391'
    Password: 'myownpasswd'
    Encryption: 'AES'
    Allowed-Connections: []

Hosts:
  'default':
    Enabled: true
    Display: 'Default'
    Driver: 'BUILT-IN'
    Address: '127.0.0.1'
    Port-Range: '20000-21000'
    Directory: './servers'
    Git-Bash: '$HOME/.git'

Servers:
  'lobby':
    Enabled: true
    Display: 'Lobby'
    Host: 'default'
    Group:
    - 'lobby'
    Port: 20000
    Motd: ''
    Log: false
    Directory: 'lobby'
    Executable: 'java -server -Djline.terminal=jline.UnsupportedTerminal -Dcom.mojang.eula.agree=true -Dfile.encoding=UTF-8 -jar paperclip.jar -p 20000 -w lobby -h 127.0.0.1 -W worlds --log-strip-color -s 200 -o false -b ../#configs/bukkit.yml -c ../#configs/server.properties -S ../#configs/spigot.yml --paper ../#configs/paper.yml'
    Stop-Command: 'stop'
    Stop-Action: 'RESTART'
    Run-On-Launch: true
    Restricted: false
    Incompatible: []
    Hidden: false
  'event':
    Enabled: true
    Display: 'Event'
    Host: 'default'
    Group:
    - 'event'
    Port: 20001
    Motd: ''
    Log: false
    Directory: 'event'
    Executable: 'java -server -Djline.terminal=jline.UnsupportedTerminal -Dcom.mojang.eula.agree=true -Dfile.encoding=UTF-8 -jar paperclip.jar -p 20001 -w world -h 127.0.0.1 -W worlds --log-strip-color -s 200 -o false -b ../#configs/bukkit.yml -c ../#configs/server.properties -S ../#configs/spigot.yml --paper ../#configs/paper.yml'
    Stop-Command: 'stop'
    Stop-Action: 'RESTART'
    Run-On-Launch: true
    Restricted: false
    Incompatible: []
    Hidden: false
```
SubServer-Cliend Config:
```
Settings:
  Version: '2.11.2a+'
  Ingame-Access: true
  Show-Addresses: false
  Use-Title-Messages: false
  SubData:
    Address: '127.0.0.1:4391'
    Password: 'myownpasswd'
    Encryption: 'AES'
```

### How It Happened
SubServers.Client.Bukkit.jar doesn't work.

### Additional Information
Using Paperclip and HexaCord (not Spigot and BungeeCord)

**Comment by ME1312** [comment]
Try updating it to the latest dev build to match `18w49a`

**Comment by xXSchrandXx** [comment]
Worked
