### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#30]
### Platform Information
 https://src.me1312.net/jenkins/job/SubServers%20Platform/lastSuccessfulBuild/artifact/Artifacts/SubServers.Bungee.jar downloaded 11.01.2019 17:47

### What Happened
```
*******************************************
***  Warning: this build is unofficial  ***
***                                     ***
*** Please report all issues to ME1312, ***
***   NOT the Spigot Team. Thank You!   ***
*******************************************
*** Problem checking BungeeCord version ***
***    BungeeCord could be outdated.    ***
***                                     ***
*** Errors may arise on older versions! ***
*******************************************

17:43:28 [INFO] Using mbed TLS based native cipher.
17:43:28 [INFO] Using zlib based native compressor.
17:43:28 [INFO] SubServers > Loading SubServers.Bungee v2.13.2c Libraries (for Minecraft 1.13.x)
17:43:28 [SEVERE] Exception in thread "main"
17:43:28 [SEVERE] java.lang.NullPointerException
17:43:28 [SEVERE]     at net.ME1312.SubServers.Bungee.SubPlugin.<init>(SubPlugin.java:91)
17:43:28 [SEVERE]     at net.ME1312.SubServers.Bungee.Launch.main(Launch.java:114)
```

### How It Happened
Executing: java -Xms$MINRAM -Xmx$MAXRAM -Dfile.encoding=UTF-8 -jar SubServers.Bungee.jar

### Additional Information
none

**Comment by xXSchrandXx** [comment]
[Sourcecode](https://github.com/ME1312/SubServers-2/blob/6218b873ca0f8f60b77219e173ac96bddb835d19/SubServers.Bungee/src/net/ME1312/SubServers/Bungee/SubPlugin.java#L91) says the config version is null. But in my config it is 2.11.2a+.

**Comment by xXSchrandXx** [comment]
Sry, found it...
'Settings' was written to 'ettings', don't know why.
