### ISSUE TITLE
19w21c PROTOCOL_MISMATCH

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#44]
### Platform Information
``` LOG
[08:16:34] [BungeeCord/INFO] > SubServers > These are the platforms and versions that are running SubServers.Bungee:
[08:16:34] [BungeeCord/INFO] >   Linux 3.16.0-4-amd64 [x64],
[08:16:34] [BungeeCord/INFO] >   Java 1.8.0_191 [x64],
[08:16:34] [BungeeCord/INFO] >   GalaxiEngine v3.2.0c (19w21a),
[08:16:34] [BungeeCord/INFO] >   GalaxiBungee v1.14a (19w21c),
[08:16:34] [BungeeCord/INFO] >   SubServers.Bungee v2.14a (19w21c)
[08:16:34] [BungeeCord/INFO] >
[08:16:34] [BungeeCord/INFO] > You are on the latest version.
```

### What Happened
``` LOG
[08:14:16] [SubData/ERROR] > java.lang.IllegalStateException: /127.0.0.1:55437: Only InitPacketDeclaration (0x0000) may be received during the PRE_INITIALIZATION stage: [0xC479, 0xFEE6]
[08:14:16] [SubData/ERROR] > 	at net.ME1312.SubData.Server.SubDataClient.read(SubDataClient.java:111)
[08:14:16] [SubData/ERROR] > 	at net.ME1312.SubData.Server.SubDataClient.lambda$null$2(SubDataClient.java:213)
[08:14:16] [SubData/ERROR] > 	at java.lang.Thread.run(Thread.java:748)
[08:14:16] [SubData/WARN] > /127.0.0.1:55437 has disconnected: PROTOCOL_MISMATCH
```

### How It Happened
Don't know.

### Additional Information
Does `SubServers-Client-Bukkit/config.yml`'s `Settings.SubData.Name` effect this?
Because I do have symlinked this config to every Minecraft Server and it does only say `undefined`.

**Comment by ME1312** [comment]
SubServers 2.14a is not network compatible with the last version because [it uses the next evolution of SubData.](https://github.com/ME1312/SubData-2) So to solve this, make sure all SubServers apps are using builds with the same signature (`19w21c` in your case).

**Comment by xXSchrandXx** [comment]
I am using `19w21c` on every SubServers app...
It only is `SubServers.Bungee` and `SubServers.Client.Bukkit`.

Only GalaxyEngine is on `19w21a`. But that's not a SubServer-App, is it?

**Comment by ME1312** [comment]
Yes, GalaxiEngine and GalaxiBungee are both unrelated in this case.

To explain a little further, this error is a [safe-guard that keeps things that aren't SubData off the SubData network.](https://github.com/ME1312/SubData-2/wiki/Protocol-States#pre_initialization) So, if your apps are running the same version (and working properly together), that means some unknown app is connecting on `4391`.
