### ISSUE TITLE
SubServers.Host startup fail

### ISSUE THREAD

**Issue by xXSchrandXx** [ME1312/SubServers-2#45]
### Platform Information
```
$ java -jar SubServers.Host.jar -v

Linux 3.16.0-4-amd64 [x64],
Java 1.8.0_191 [x64],
GalaxiEngine v3.2.0c (19w22a),
SubServers.Host v2.14a (19w22a)
```

### What Happened
Starting SubServer.Host.jar with a chrooted User:
```
$ java -jar SubServers.Host.jar
Exception in thread "main" java.lang.NullPointerException
        at net.ME1312.SubServers.Host.ExHost.<init>(ExHost.java:231)
        at net.ME1312.SubServers.Host.ExHost.main(ExHost.java:126)
        at net.ME1312.SubServers.Host.Launch.main(Launch.java:28)
```

### Additional Information
Chrooted User does can use java (Paperspigot does start normal)

**Comment by ME1312** [comment]
It seems that this is a rare instance where something went wrong before the engine was started. Unfortunately, SubServers.Host was not equipped to handle such problems and so the error handler is actually the one that threw that error. 🤔 

Anyway, since this issue does not show up in my tests, I'm going to have to ask you to re-run the app with `19w22b` to get to the root cause of of the issue.

**Comment by xXSchrandXx** [comment]
Now:
```
$ java -jar SubServers.Host.jar -version

Linux 3.16.0-4-amd64 [x64],
Java 1.8.0_191 [x64],
GalaxiEngine v3.2.0c (19w22b),
SubServers.Host v2.14a (19w22b)
```

Error:
```
$ javax.imageio.IIOException: Can't create cache file!
         at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:361)
         at javax.imageio.ImageIO.read(ImageIO.java:1351)
         at net.ME1312.Galaxi.Plugin.PluginInfo.setIcon(PluginInfo.java:238)
         at net.ME1312.SubServers.Host.ExHost.<init>(ExHost.java:142)
         at net.ME1312.SubServers.Host.ExHost.main(ExHost.java:126)
         at net.ME1312.SubServers.Host.Launch.main(Launch.java:28)
 Caused by: java.nio.file.NoSuchFileException: /tmp/imageio7788045188081258097.tmp
         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
         at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
         at java.nio.file.Files.newByteChannel(Files.java:361)
         at java.nio.file.Files.createFile(Files.java:632)
         at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
         at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
         at java.nio.file.Files.createTempFile(Files.java:897)
         at javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:102)
         at com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(InputStreamImageInputStreamSpi.java:69)
         at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
         ... 5 more
```

**Comment by xXSchrandXx** [comment]
My Bad, the chroot was not set up correctly.
