### ISSUE TITLE
subserver client not working and a stack trace

### ISSUE THREAD

**Issue by compieter-gh** [ME1312/SubServers-2#49]
Plugins (21): BanItem, ChatCo*, ClearLag, Ersatz*, IllegalStack, LuckPerms, PlaceholderAPI, ProtocolLib, ServerAge*, SkinsRestorer, Skript, Skungee*, SubServers-Client-Bukkit*, TAB, Vault, ViaBackwards, ViaRewind, ViaRewindPotions*, ViaVersion, Votifier, WorldEdit

[00:37:27 INFO]: SubServers > These are the platforms and versions that are running SubServers.Bungee:
[00:37:27 INFO]:   Linux 4.15.0-76-generic [x64],
[00:37:27 INFO]:   Java 11.0.6 [x64],
[00:37:27 INFO]:   Waterfall git:Waterfall-Bootstrap:1.15-SNAPSHOT:a16947e:318,
[00:37:27 INFO]:   SubServers.Bungee v2.15a revision 3 (20w04a)
[00:37:27 INFO]:
[00:37:27 INFO]: You are on the latest version.

[00:28:38 INFO]: creative_anarchy > ComPieter issued server command: /sub restart creative
[00:28:38 WARN]: creative_anarchy > java.lang.IllegalStateException: There are no lang options available at this time
[00:28:38 WARN]: creative_anarchy > at net.ME1312.SubServers.Client.Bukkit.SubCommand.execute(SubCommand.java:50)
[00:28:38 WARN]: creative_anarchy > at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[00:28:38 WARN]: creative_anarchy > at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1820)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
[00:28:38 WARN]: creative_anarchy > at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
[00:28:38 WARN]: creative_anarchy > at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ME1312** [comment]
This issue is usually caused by the initial attempt (and subsequent attempts) at a SubData connection failing, thus denying the plugin from downloading lang options. For a more specific description of the problem, you can scroll up in your logs to when the connection was being made. (It's probably right after the server finished starting.)

If you are trying to add SubServers.Client to an existing server, make sure you have read the [installation instructions](https://github.com/ME1312/SubServers-2/wiki/Install#subserversclient).

**Comment by compieter-gh** [comment]
hmm i restarted the server and now it downloaded the lang settings maybe this isn't caused by an plugin maybe it's my linux server or could it be that starting all the servers at once when i first start subservers that it oveloads subdata with connections? i am going to investigate further.

[17:36:25 INFO]: creative_anarchy > SubServers > Loading SubServers.Client.Bukkit v2.15a Libraries (for Minecraft 1.15.2)
[17:36:25 ERROR]: creative_anarchy > [Votifier] Votifier was not able to bind to /0.0.0.0:8192
[17:36:25 INFO]: creative_anarchy > SubData > RSA Encryption Available
[17:36:25 INFO]: creative_anarchy > SubData >
[17:36:25 INFO]: creative_anarchy > SubData > Connecting to /127.0.0.1:4391
[17:36:28 INFO]: creative_anarchy > SubData > Logged into /127.0.0.1:4391
[17:36:29 INFO]: creative_anarchy > SubData > Lang Settings Downloaded

**Comment by compieter-gh** [comment]
@ME1312 this issue seems too happen only when i start all 10 servers at once when i restart one server after that for example hub it's just works fine if you want i can send the whole startup log based on what im seening it connects too the server and it downloads the lang setting but then says it didn't download it very wierd issue

**Comment by TheCompieter** [comment]
another update on this i think it may have too do with an java incompatibility especially java 11
i downgraded to java 8 cause i didn't know i was on java 11 in the first place and it now seems too work every time so far as i have tested i will close this issue when no further issues come regarding this

**Comment by ME1312** [comment]
There isn't a whole lot I can do if the lang settings are reporting that they have indeed downloaded, since [if it didn't it would definitely throw an error instead](https://github.com/ME1312/SubServers-2/blob/master/SubServers.Client/Bukkit/src/net/ME1312/SubServers/Client/Bukkit/Network/Packet/PacketDownloadLang.java#L39-L40).

The best option then is probably just to space the servers out a bit so they don't run into each other. This can be done with [`Run-On-Launch-Timeout`](https://github.com/ME1312/SubServers-2/wiki/Configuration#subserversserversyml-global-configuration).

**Comment by compieter-gh** [comment]
Thanks I will try that

**Comment by compieter-gh** [comment]
[07:31:56] [SubServers.Bungee::Internal_Log_Spooler(creative_anarchy)/INFO]: creative_anarchy > SubData > Connected to /127.0.0.1:4391
[07:31:56] [SubServers.Bungee::Internal_Log_Spooler(creative_anarchy)/ERROR]: creative_anarchy > SubData > java.io.IOException: Pipe not connected
[07:31:56] [SubServers.Bungee::Internal_Log_Spooler(creative_anarchy)/INFO]: creative_anarchy > 	at java.io.PipedInputStream.read(PipedInputStream.java:305)
[07:31:56] [SubServers.Bungee::Internal_Log_Spooler(creative_anarchy)/INFO]: creative_anarchy > 	at net.ME1312.SubData.Client.SubDataClient.read(SubDataClient.java:75)
[07:31:56] [SubServers.Bungee::Internal_Log_Spooler(creative_anarchy)/INFO]: creative_anarchy > 	at net.ME1312.SubData.Client.SubDataClient.lambda$null$2(SubDataClient.java:214)
[07:31:56] [SubServers.Bungee::Internal_Log_Spooler(creative_anarchy)/INFO]: creative_anarchy > 	at java.lang.Thread.run(Thread.java:748)
[07:31:56] [SubServers.Bungee::Internal_Log_Spooler(creative_anarchy)/INFO]: creative_anarchy > 
[07:31:56] [SubServers.Bungee::Internal_Log_Spooler(creative_anarchy)/WARN]: creative_anarchy > SubData > Disconnected from /127.0.0.1:4391: UNHANDLED_EXCEPTION
[07:31:56] [SubServers.Bungee::Internal_Log_Spooler(creative_anarchy)/INFO]: creative_anarchy > SubData > Attempting reconnect in 30 seconds

[07:31:55] [SubDataServer::Data_Listener(/127.0.0.1:45356)/WARN]: SubData > /127.0.0.1:45356 has disconnected: CONNECTION_INTERRUPTED

yep it failed again with 30 sec start timeout maybe longer time out or something else

**Comment by compieter-gh** [comment]
also failed with 60 secs timeout :/ this was after it finished starting the hub

[07:42:51 INFO]: hub > SubData > Connected to /127.0.0.1:4391
[07:42:51 ERROR]: hub > SubData > java.io.IOException: Pipe not connected
[07:42:51 INFO]: hub >        at java.io.PipedInputStream.read(PipedInputStream.java:305)
[07:42:51 INFO]: hub >        at net.ME1312.SubData.Client.SubDataClient.read(SubDataClient.java:75)
[07:42:51 INFO]: hub >        at net.ME1312.SubData.Client.SubDataClient.lambda$null$2(SubDataClient.java:214)
[07:42:51 INFO]: hub >        at java.lang.Thread.run(Thread.java:748)
[07:42:51 INFO]: hub >
[07:42:51 WARN]: hub > [ViaVersion] You are running a development version, please report any bugs to GitHub.
[07:42:51 WARN]: hub > SubData > Disconnected from /127.0.0.1:4391: UNHANDLED_EXCEPTION

hmmm wierd i tried to do /sub and it took like 30 secs too open but it seems too work now imma just wait on your feedback here's the info of my waterfall

[07:48:50 INFO]: SubServers > These are the platforms and versions that are running SubServers.Bungee:
[07:48:50 INFO]:   Linux 4.15.0-76-generic [x64],
[07:48:50 INFO]:   Java 1.8.0_242 [x64],
[07:48:50 INFO]:   Waterfall git:Waterfall-Bootstrap:1.15-SNAPSHOT:a16947e:318,
[07:48:50 INFO]:   SubServers.Bungee v2.15a revision 3 (20w04a)

and the paper version that im running is 1.15.2 build 99 for all servers

the next step is what i'm going too do is reinstall ubuntu server 18.04.3 and setup everything again had too do that anyway cause of old stuff etc

**Comment by ME1312** [comment]
It seems that issue (specifically) was that an internal SubData thread was started too quickly the first time. As for why it works 30 seconds later, that's just because it tried reconnecting again (which is normal) and didn't run into that problem.

The latest snapshot of SubServers has a change that may prevent this from happening in the future. Although it uses a newer revision of SubData all together, so make sure to update all the apps to this version if you're trying it out.

**Comment by compieter-gh** [comment]
Okay thanks it's fixed now i updated subservers and had too update the subservers.client on every server too but now it indeed doesn't seem to run into that problem
