### ISSUE TITLE
Unknown encryption type "RSA"

### ISSUE THREAD

**Issue by ryanrox333** [ME1312/SubServers-2#58]
### Platform Information
```
> 00:45:39 [INFO] Linux 5.4.0-1037-aws [x64],
> 00:45:39 [INFO] Java 1.8.0_282 [x64],
>> 00:45:39 [INFO] BungeeCord git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:3d701fb:1545,
> 00:45:39 [INFO] SubServers.Bungee v2.17a (21w07b)
```

### What Happened
When I use the Client on my hub server. I get an ENCRYPTION_MISMATCH error.

### How It Happened
I added the client plugin to my hub.
I restarted my hub.
I got the following error:
```
[00:42:02 INFO]: SubData > Connected to /127.0.0.1:4391
[00:42:02 ERROR]: SubData > net.ME1312.SubData.Client.Library.Exception.EncryptionException: Unknown encryption type "RSA"
at net.ME1312.SubData.Client.Protocol.Initial.InitPacketChangeEncryption.receive(InitPacketChangeEncryption.java:49)
at net.ME1312.SubData.Client.Protocol.PacketObjectIn.receive(PacketObjectIn.java:32)
at net.ME1312.SubData.Client.SubDataClient.lambda$read$6(SubDataClient.java:180)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
at java.lang.Thread.run(Thread.java:748)

[00:42:02 WARN]: SubData > Disconnected from /127.0.0.1:4391: ENCRYPTION_MISMATCH
```

**Comment by ME1312** [comment]
Sometimes I wonder why I traded better instructions for more encryption options.
```
[22:39:56 INFO]: SubData > Encrypting SubData with RSA:
[22:39:56 INFO]: SubData > Copy your subdata.rsa.key to clients to allow them to connect
[22:39:56 INFO]: SubData >
[22:39:56 INFO]: SubData > Listening on /0.0.0.0:4391
```
