### ISSUE TITLE
Can't join Lobby server after creating

### ISSUE THREAD

**Issue by MadeByIToncek** [ME1312/SubServers-2#59]
### Platform Information
Paste in the version information from the SubServers app in question here. To get this info, run the `/sub version` command where applicable or launch SubServers with the `-v` argument. Make sure the app name matches the one you are reporting this bug for.

Windows 10 (19041.804) [x64],
Java 1.8.0_281 [x64],
BungeeCord git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:4f23b49:1548,
SubServers.Bungee v2.17a (21w08a)

### What Happened
Here you can write about what happened that shouldn't have. If you have any errors in your console related to what happened, you should also paste those here.

I can't join Lobby server after creating. It throws this error: 

09:54:05 [SEVERE] ?no 16, 2021 9:54:05 DOP. io.netty.util.concurrent.AbstractEventExecutor safeExecute
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@5ad4e21a
java.lang.NullPointerException: info
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
    at net.md_5.bungee.UserConnection.connect(UserConnection.java:252)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:550)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Unknown Source)

and client stay at ```Joining world...``` and then throws Timeout

### How It Happened
Tell us step-by-step how to recreate the problem. This step is vital for us to determine whether or not the problem happens to everyone else too.

* 1. Create new Lobby server (from any server software, it happens for all softwares)
* 2. After finishing installation: Join the server.

### Additional Information
Here you can provide any extra details you may think useful for solving the problem.

**Comment by ME1312** [comment]
Hi. Please make sure the names of servers in BungeeCord's priorities list match up exactly (it's case-sensitive) with either an existing server, or the server you are trying to create.
