### ISSUE TITLE
 "There are no lang options available at this time"

### ISSUE THREAD

**Issue by Kovacs37** [ME1312/SubServers-2#6]
Hi,

I tested SubServer on my windows computer, and, no problems, everything worked. But when i tried to put it on my linux server, i can create any servers I want, but there are a lot of problems, and I don't know what problem cause the impossibility of doing /sub ingame..

When I start a server using /sub start <name> i have this error : 
19:05:27 [INFO] mexico > SubData > Could not link name with server: There is no server with that name
(the server is called mexico, don't ask me why)

and then, when i'm in game and I try a /sub the console output is : 

```
19:06:38 [INFO] mexico > Kovacs issued server command: /sub
19:06:38 [WARNING] mexico > java.lang.IllegalStateException: There are no lang o                                                                                                 ptions available at this time
19:06:38 [WARNING] mexico > at net.ME1312.SubServers.Client.Bukkit.SubCommand.on                                                                                                 Command(SubCommand.java:33)
19:06:38 [WARNING] mexico > at org.bukkit.command.PluginCommand.execute(PluginCo                                                                                                 mmand.java:44)
19:06:38 [WARNING] mexico > at org.bukkit.command.SimpleCommandMap.dispatch(Simp                                                                                                 leCommandMap.java:141)
19:06:38 [WARNING] mexico > at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispa                                                                                                 tchCommand(CraftServer.java:650)
19:06:38 [WARNING] mexico > at net.minecraft.server.v1_11_R1.PlayerConnection.ha                                                                                                 ndleCommand(PlayerConnection.java:1353)
19:06:38 [WARNING] mexico > at net.minecraft.server.v1_11_R1.PlayerConnection.a(                                                                                                 PlayerConnection.java:1188)
19:06:38 [WARNING] mexico > at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(                                                                                                 PacketPlayInChat.java:45)
19:06:38 [WARNING] mexico > at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(                                                                                                 PacketPlayInChat.java:1)
19:06:38 [WARNING] mexico > at net.minecraft.server.v1_11_R1.PlayerConnectionUti                                                                                                 ls$1.run(SourceFile:13)
19:06:38 [WARNING] mexico > at java.util.concurrent.Executors$RunnableAdapter.ca                                                                                                 ll(Executors.java:511)
19:06:38 [WARNING] mexico > at java.util.concurrent.FutureTask.run(FutureTask.ja                                                                                                 va:266)
19:06:38 [WARNING] mexico > at net.minecraft.server.v1_11_R1.SystemUtils.a(Sourc                                                                                                 eFile:46)
19:06:38 [WARNING] mexico > at net.minecraft.server.v1_11_R1.MinecraftServer.D(M                                                                                                 inecraftServer.java:747)
19:06:38 [WARNING] mexico > at net.minecraft.server.v1_11_R1.DedicatedServer.D(D                                                                                                 edicatedServer.java:399)
19:06:38 [WARNING] mexico > at net.minecraft.server.v1_11_R1.MinecraftServer.C(M                                                                                                 inecraftServer.java:678)
19:06:38 [WARNING] mexico > at net.minecraft.server.v1_11_R1.MinecraftServer.run                                                                                                 (MinecraftServer.java:576)
19:06:38 [WARNING] mexico > at java.lang.Thread.run(Thread.java:745)
```

Can you help me ?..
I tried to reset many and many time and redo the complete installation but it don't work..

**Comment by ME1312** [comment]
Hey,
This looks to me like a SubData connection issue. What's it look like when it starts up? Also, please run 'sub version' in your bungee console.

The error means it hasn't yet downloaded lang.yml, so it is unable to produce any sort of message to who sent the command.

**Comment by Kovacs37** [comment]
Hi,

``
```
root@fineserv:/home/kovacs/FSX# java -jar SubServers.Bungee.jar

*******************************************
***  Warning: this build is Unofficial  ***
***                                     ***
*** Please report all issues to ME1312, ***
***   NOT the Spigot Team. Thank You!   ***
*******************************************

12:43:11 [INFO] Using OpenSSL based native cipher.
12:43:11 [INFO] Using native code compressor
12:43:11 [INFO] SubServers > Loading SubServers v2.11.2l Libraries...
12:43:11 [INFO] SubServers > Loading BungeeCord Libraries...
12:43:11 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:53cc324:1229
12:43:11 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
12:43:11 [INFO] Epoll is working, utilising it!
12:43:11 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
12:43:11 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
12:43:11 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
12:43:11 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
12:43:11 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
12:43:11 [INFO] Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
12:43:11 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
12:43:11 [INFO] Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
12:43:12 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
12:43:12 [INFO] Enabled plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
12:43:12 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
12:43:12 [INFO] Enabled plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
12:43:12 [INFO] SubServers > SubData Direct Listening on /127.0.0.1:4391
12:43:12 [INFO] SubServers > Loading Hosts...
12:43:12 [INFO] SubServers > Loading Servers...
12:43:12 [INFO] SubServers > Loading SubServers...
12:43:12 [INFO] SubServers > 1 Host, 0 Servers, and 3 SubServers loaded in 110ms
12:43:12 [SEVERE] Apr 20, 2017 12:43:12 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 59:e5:32:6d:7f:5a:10:24

12:43:12 [INFO] Listening on /0.0.0.0:27777
>sub start mexico
12:43:37 [INFO] SubServers > Now starting mexico
12:43:38 [INFO] mexico > Loading libraries, please wait...
12:43:44 [INFO] mexico > Starting minecraft server version 1.11.2
12:43:44 [INFO] mexico > Loading properties
12:43:44 [WARNING] mexico > You have used the Spigot command line EULA agreement flag.
12:43:44 [WARNING] mexico > By using this setting you are indicating your agreement to Mojang's EULA (https://account.mojang.com/documents/minecraft_eula).
12:43:44 [WARNING] mexico > If you do not agree to the above EULA please stop your server and remove this flag immediately.
12:43:44 [INFO] mexico > Default game type: SURVIVAL
12:43:44 [INFO] mexico > This server is running CraftBukkit version git-Spigot-54ec0b8-be9ef98 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
12:43:44 [INFO] mexico > Server Ping Player Sample Count: 12
12:43:44 [INFO] mexico > Using 4 threads for Netty based IO
12:43:44 [INFO] mexico > Debug logging is disabled
12:43:45 [INFO] mexico > Generating keypair
12:43:45 [INFO] mexico > Starting Minecraft server on 127.0.0.1:27799
12:43:45 [INFO] mexico > Using epoll channel type
12:43:45 [INFO] mexico > Set PluginClassLoader as parallel capable
12:43:45 [INFO] mexico > [SubServers-Client-Bukkit] Loading SubServers-Client-Bukkit v2.11.2g
12:43:45 [WARNING] mexico > **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
12:43:45 [WARNING] mexico > The server will make no attempt to authenticate usernames. Beware.
12:43:45 [WARNING] mexico > Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
12:43:45 [WARNING] mexico > Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
12:43:45 [WARNING] mexico > To change this, set "online-mode" to "true" in the server.properties file.
12:43:45 [INFO] mexico > **** Beginning UUID conversion, this may take A LONG time ****
12:43:45 [INFO] mexico > Preparing level "world"
12:43:45 [INFO] mexico > -------- World Settings For [world] --------
12:43:45 [INFO] mexico > Cactus Growth Modifier: 100%
12:43:45 [INFO] mexico > Cane Growth Modifier: 100%
12:43:45 [INFO] mexico > Melon Growth Modifier: 100%
12:43:45 [INFO] mexico > Mushroom Growth Modifier: 100%
12:43:45 [INFO] mexico > Pumpkin Growth Modifier: 100%
12:43:45 [INFO] mexico > Sapling Growth Modifier: 100%
12:43:45 [INFO] mexico > Wheat Growth Modifier: 100%
12:43:45 [INFO] mexico > NetherWart Growth Modifier: 100%
12:43:45 [INFO] mexico > Vine Growth Modifier: 100%
12:43:45 [INFO] mexico > Cocoa Growth Modifier: 100%
12:43:45 [INFO] mexico > Entity Activation Range: An 32 / Mo 32 / Mi 16
12:43:45 [INFO] mexico > Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
12:43:45 [INFO] mexico > Mob Spawn Range: 4
12:43:45 [INFO] mexico > Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
12:43:45 [INFO] mexico > Random Lighting Updates: false
12:43:45 [INFO] mexico > Structure Info Saving: true
12:43:45 [INFO] mexico > Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
12:43:45 [INFO] mexico > Max TNT Explosions: 100
12:43:45 [INFO] mexico > Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
12:43:45 [INFO] mexico > Allow Zombie Pigmen to spawn from portal blocks: true
12:43:45 [INFO] mexico > Item Despawn Rate: 6000
12:43:45 [INFO] mexico > Item Merge Radius: 2.5
12:43:45 [INFO] mexico > Arrow Despawn Rate: 1200
12:43:45 [INFO] mexico > View Distance: 10
12:43:45 [INFO] mexico > Experience Merge Radius: 3.0
12:43:45 [INFO] mexico > Zombie Aggressive Towards Villager: true
12:43:45 [INFO] mexico > Nerfing mobs spawned from spawners: false
12:43:45 [INFO] mexico > -------- World Settings For [world_nether] --------
12:43:45 [INFO] mexico > Cactus Growth Modifier: 100%
12:43:45 [INFO] mexico > Cane Growth Modifier: 100%
12:43:45 [INFO] mexico > Melon Growth Modifier: 100%
12:43:45 [INFO] mexico > Mushroom Growth Modifier: 100%
12:43:45 [INFO] mexico > Pumpkin Growth Modifier: 100%
12:43:45 [INFO] mexico > Sapling Growth Modifier: 100%
12:43:45 [INFO] mexico > Wheat Growth Modifier: 100%
12:43:45 [INFO] mexico > NetherWart Growth Modifier: 100%
12:43:45 [INFO] mexico > Vine Growth Modifier: 100%
12:43:45 [INFO] mexico > Cocoa Growth Modifier: 100%
12:43:45 [INFO] mexico > Entity Activation Range: An 32 / Mo 32 / Mi 16
12:43:45 [INFO] mexico > Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
12:43:45 [INFO] mexico > Mob Spawn Range: 4
12:43:45 [INFO] mexico > Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
12:43:45 [INFO] mexico > Random Lighting Updates: false
12:43:45 [INFO] mexico > Structure Info Saving: true
12:43:45 [INFO] mexico > Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
12:43:45 [INFO] mexico > Max TNT Explosions: 100
12:43:45 [INFO] mexico > Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
12:43:45 [INFO] mexico > Allow Zombie Pigmen to spawn from portal blocks: true
12:43:45 [INFO] mexico > Item Despawn Rate: 6000
12:43:45 [INFO] mexico > Item Merge Radius: 2.5
12:43:45 [INFO] mexico > Arrow Despawn Rate: 1200
12:43:45 [INFO] mexico > View Distance: 10
12:43:45 [INFO] mexico > Experience Merge Radius: 3.0
12:43:45 [INFO] mexico > Zombie Aggressive Towards Villager: true
12:43:45 [INFO] mexico > Nerfing mobs spawned from spawners: false
12:43:45 [INFO] mexico > -------- World Settings For [world_the_end] --------
12:43:45 [INFO] mexico > Cactus Growth Modifier: 100%
12:43:45 [INFO] mexico > Cane Growth Modifier: 100%
12:43:45 [INFO] mexico > Melon Growth Modifier: 100%
12:43:45 [INFO] mexico > Mushroom Growth Modifier: 100%
12:43:45 [INFO] mexico > Pumpkin Growth Modifier: 100%
12:43:45 [INFO] mexico > Sapling Growth Modifier: 100%
12:43:45 [INFO] mexico > Wheat Growth Modifier: 100%
12:43:45 [INFO] mexico > NetherWart Growth Modifier: 100%
12:43:45 [INFO] mexico > Vine Growth Modifier: 100%
12:43:45 [INFO] mexico > Cocoa Growth Modifier: 100%
12:43:45 [INFO] mexico > Entity Activation Range: An 32 / Mo 32 / Mi 16
12:43:45 [INFO] mexico > Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
12:43:45 [INFO] mexico > Mob Spawn Range: 4
12:43:45 [INFO] mexico > Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
12:43:45 [INFO] mexico > Random Lighting Updates: false
12:43:45 [INFO] mexico > Structure Info Saving: true
12:43:45 [INFO] mexico > Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
12:43:45 [INFO] mexico > Max TNT Explosions: 100
12:43:45 [INFO] mexico > Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
12:43:45 [INFO] mexico > Allow Zombie Pigmen to spawn from portal blocks: true
12:43:45 [INFO] mexico > Item Despawn Rate: 6000
12:43:45 [INFO] mexico > Item Merge Radius: 2.5
12:43:45 [INFO] mexico > Arrow Despawn Rate: 1200
12:43:45 [INFO] mexico > View Distance: 10
12:43:45 [INFO] mexico > Experience Merge Radius: 3.0
12:43:45 [INFO] mexico > Zombie Aggressive Towards Villager: true
12:43:45 [INFO] mexico > Nerfing mobs spawned from spawners: false
12:43:45 [INFO] mexico > Preparing start region for level 0 (Seed: -6512882691086079474)
12:43:46 [INFO] mexico > Preparing spawn area: 22%
12:43:47 [INFO] mexico > Preparing spawn area: 70%
12:43:48 [INFO] mexico > Preparing start region for level 1 (Seed: -6512882691086079474)
12:43:49 [INFO] mexico > Preparing spawn area: 87%
12:43:49 [INFO] mexico > Preparing start region for level 2 (Seed: -6512882691086079474)
12:43:49 [INFO] mexico > [SubServers-Client-Bukkit] Enabling SubServers-Client-Bukkit v2.11.2g
12:43:49 [INFO] mexico > SubServers > Loading SubServers v2.11.2g Libraries...
12:43:49 [INFO] SubData > /127.0.0.1:57442 has connected
12:43:49 [INFO] mexico > Server permissions file permissions.yml is empty, ignoring it
12:43:49 [INFO] mexico > Done (4.263s)! For help, type "help" or "?"
12:43:49 [INFO] mexico > Starting GS4 status listener
12:43:49 [INFO] mexico > Query running on 127.0.0.1:27799
12:43:50 [INFO] SubData > /127.0.0.1:57442 logged in
12:43:50 [INFO] mexico > SubData > Could not link name with server: There is no server with that name
`
```

The lang.yml exists and his version is : Version: '2.11.2a+': 
`root@fineserv:/home/kovacs/FSX/SubServers# ls
Templates  build.sh  config.yml  lang.yml
`

Finally, the version of SubServers.bungee is : 

12:47:33 [INFO] SubServers > SubServers.Bungee is running version 2.11.2l BETA 1
>

**Comment by ME1312** [comment]
Somewhere along the line I required the server to become linked properly with the name it was given. This can be fixed relatively easily on your end.

If you updated from an older version of subservers.client, you may have a folder named "SubServers" in `~mexico/plugins`. Rename that folder "SubServers-Client-Bukkit"

Otherwise, fill in the server information in `~mexico/plugins/SubServers-Bukkit-Client/config.yml`

**Comment by Kovacs37** [comment]
Hello,
Yeah, in the config file, the line : 
        Name: "undefined"
must be replaced by
        Name: 'mexico'

Thank you !

**Comment by Kovacs37** [comment]
But, my question is why it isn't automatic ? Why must I do it manually ?

I think it's because of this error I get when I create a subserver :   

`] mexico > Kovacs issued server command: /sub
16:56:42 [INFO] ~/Creator > Generating Server Files...
16:56:42 [SEVERE] java.io.FileNotFoundException: ./usa/plugins/Subservers-Client                                                                                                                               -Bukkit/config.yml (No such file or directory)
16:56:42 [SEVERE]     at java.io.FileOutputStream.open0(Native Method)
16:56:42 [SEVERE]     at java.io.FileOutputStream.open(FileOutputStream.java:270                                                                                                                               )
16:56:42 [SEVERE]     at java.io.FileOutputStream.<init>(FileOutputStream.java:2                                                                                                                               13)
16:56:42 [SEVERE]     at java.io.FileOutputStream.<init>(FileOutputStream.java:1                                                                                                                               62)
16:56:42 [SEVERE]     at java.io.FileWriter.<init>(FileWriter.java:90)
16:56:42 [SEVERE]     at net.ME1312.SubServers.Bungee.Library.Config.YAMLConfig.                                                                                                                               save(YAMLConfig.java:75)
16:56:42 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubC                                                                                                                               reator.generateClient(InternalSubCreator.java:270)
16:56:42 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubC                                                                                                                               reator.run(InternalSubCreator.java:64)
16:56:42 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubC                                                                                                                               reator.lambda$create$0(InternalSubCreator.java:212)
16:56:42 [SEVERE]     at java.lang.Thread.run(Thread.java:745)
`

**Comment by ME1312** [comment]
It is meant to be automatic, however it couldn't save the file. I'll post a new beta later with something that might help

**Comment by Kovacs37** [comment]
Thank you!

**Comment by Kovacs37** [comment]
Hello,

I saw that you posted a new beta and I have again an error :  
`Port> [RAM]
>sub create Lobby ~ spigot 1.11.2 2327
12:09:35 [INFO] ~/Creator > Generating Server Files...
12:09:35 [SEVERE] java.io.IOException: No such file or directory
12:09:35 [SEVERE]     at java.io.UnixFileSystem.createFileExclusively(Native Met                                                                                                 hod)
12:09:35 [SEVERE]     at java.io.File.createNewFile(File.java:1012)
12:09:35 [SEVERE]     at net.ME1312.SubServers.Bungee.Library.Config.YAMLConfig.                                                                                                 save(YAMLConfig.java:75)
12:09:35 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubC                                                                                                 reator.generateClient(InternalSubCreator.java:270)
12:09:35 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubC                                                                                                 reator.run(InternalSubCreator.java:64)
12:09:35 [SEVERE]     at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubC                                                                                                 reator.lambda$create$0(InternalSubCreator.java:212)
12:09:35 [SEVERE]     at java.lang.Thread.run(Thread.java:745)
12:09:35 [INFO] ~/Creator > Launching build.sh
`

The error is a little bit different, but it don't work I have the same problem. On a Windows machine it works, but it don't on my linux server, it's started with root permissions.

**Comment by ME1312** [comment]
Perhaps you should just make that folder for it (since for some reason it can't do it on it's own)
`~/SubServers/Templates/Spigot/plugins/SubServers-Client-Bukkit/`
then it should be able to generate the config.

I can't see any reason for it to be doing this in the code. Perhaps it doesn't have permission to make that folder. That wouldn't make much sense though seeing as the client can make that folder no problem.

**Comment by Kovacs37** [comment]
I launch it with the root permission.

It can generate the config file but the server is not recognized by Subserver:
Name: 'undefined'

**Comment by ME1312** [comment]
Have you tried making that folder from my last post? I cannot test for these errors since I cannot reproduce this issue. If this strategy does work, I'll add the folder to templates.zip

**Comment by ME1312** [comment]
For now, I'm going to mark this issue as closed since there hasn't been a reply in a month. I cannot recreate this issue myself, so there cannot be any progress made here at this time.
