### ISSUE TITLE
Issue on Startup of SubServers host

### ISSUE THREAD

**Issue by morgan2233** [ME1312/SubServers-2#60]
### Platform Information
SubServers Host from Spigot
### What Happened

Error released:

```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.ME1312.Galaxi.Library.Util.reflect(Util.java:184)
        at net.ME1312.Galaxi.Engine.Library.ConsoleReader.<init>(ConsoleReader.java:66)
        at net.ME1312.Galaxi.Engine.GalaxiEngine.<init>(GalaxiEngine.java:117)
        at net.ME1312.Galaxi.Engine.GalaxiEngine.init(GalaxiEngine.java:79)
        at net.ME1312.SubServers.Host.ExHost.<init>(ExHost.java:119)
        at net.ME1312.SubServers.Host.ExHost.main(ExHost.java:102)
        at net.ME1312.SubServers.Host.Launch.main(Launch.java:29)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.ME1312.Galaxi.Library.Util.reflect(Util.java:184)
        at net.ME1312.Galaxi.Engine.Library.Log.SystemLogger.start(SystemLogger.java:36)
        ... 11 more
Caused by: java.lang.ArithmeticException: / by zero
        at net.ME1312.Galaxi.Library.Log.Logger.log(Logger.java:148)
        ... 17 more
```

### How It Happened

Started server via .sh file and then tried simple `java -jar SubServers.Host.Jar`

### Additional Information
SubServers.Bungee works perfectly fine with 0 issues

**Comment by ME1312** [comment]
This is an engine level issue I believe I fixed once before.

Launch SubServers.Host with `-v` and tell me what you get.

**Comment by morgan2233** [comment]
```
Linux 5.4.0-66-generic [x64],
Java 11.0.10 [x64],
GalaxiEngine v3.3.0a (20w15a),
SubServers.Host v2.16a (20w26d)
```

**Comment by ME1312** [comment]
SubServers.Host [build 20w30a](https://dev.me1312.net/jenkins/job/SubServers%20Platform/164/) implemented the fix for this issue and should remain compatible with release version 2.16a.
