### ISSUE TITLE
NPE when copying world

### ISSUE THREAD

**Issue by wysohn** [ME1312/SubServers-2#67]
### Platform Information
```
17:18:36 [INFO] CONSOLE executed command: /sub version
17:18:36 [INFO] SubServers > These are the platforms and versions that are running SubServers.Bungee:
17:18:36 [INFO]   Linux 5.4.0-77-generic [x64],
17:18:36 [INFO]   Java 16.0.1 [x64],
17:18:36 [INFO]   BungeeCord git:BungeeCord-Bootstrap:1.17-R0.1-SNAPSHOT:c866619:1594,
17:18:36 [INFO]   SubServers.Bungee v2.17a (21w24k)
17:18:36 [INFO] 
17:18:36 [INFO] You are on the latest version.

```

### What Happened
```
17:09:09 [SEVERE] java.lang.NullPointerException: Cannot read the array length because "<local3>" is null

17:09:09 [SEVERE] 	at net.ME1312.Galaxi.Library.Util.copyDirectory(Util.java:275)

17:09:09 [SEVERE] 	at net.ME1312.Galaxi.Library.Util.copyDirectory(Util.java:279)

17:09:09 [SEVERE] 	at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubCreator$CreatorTask.build(InternalSubCreator.java:128)

17:09:09 [SEVERE] 	at net.ME1312.SubServers.Bungee.Host.Internal.InternalSubCreator$CreatorTask.run(InternalSubCreator.java:247)
```

### How It Happened

1. `sub create` as usual with the template that has 'world' folder in it
2. the exception is thrown
3. the server is created but the 'world' folder is empty 

Any insight?

**Comment by wysohn** [comment]
seems like a permission-related issue.
