### ISSUE TITLE
Waterfall Bug

### ISSUE THREAD

**Issue by NeglectDream** [ME1312/SubServers-2#74]
[12:32:14] [main/WARN]: Error loading plugin SubServers-Console
java.lang.NoClassDefFoundError: net/ME1312/SubServers/Bungee/SubProxy
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:?]
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Unknown Source) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
Caused by: java.lang.ClassNotFoundException: net.ME1312.SubServers.Bungee.SubProxy
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 9 more

**Comment by ME1312** [comment]
SubServers.Console must be run under SubServers.Bungee &ndash; the server manager &ndash; in order to function.
