### ISSUE TITLE
Cannot create server in SubServers.Sync instance during SubServer creation

### ISSUE THREAD

**Issue by jingwenMC** [ME1312/SubServers-2#80]
### Platform Information
[18:28:23 INFO]: SubServers > These are the platforms and versions that are running SubServers.Bungee:
[18:28:23 INFO]:   Linux 3.10.0-1160.31.1.el7.x86_64 [x64],
[18:28:23 INFO]:   Java 1.8.0_292 [x64],
[18:28:23 INFO]:   Waterfall git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448,
[18:28:23 INFO]:   SubServers.Bungee v2.18a (21w52a)
[18:28:23 INFO]: 
[18:28:24 INFO]: You are on the latest version.

### What Happened
Cannot create server in SubServers.Sync instance during SubServer creation , using API
[18:24:22 ERROR]: SubData > java.lang.reflect.InvocationTargetException: /127.0.0.1:4391: Exception while running packet handler
        at net.ME1312.SubData.Client.SubDataClient.lambda$read$6(SubDataClient.java:173)
        at net.ME1312.SubData.Client.SubDataClient.read(SubDataClient.java:165)
        at net.ME1312.SubData.Client.SubDataClient.lambda$null$10(SubDataClient.java:213)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException: Illegal null value at position: [3]
        at net.ME1312.Galaxi.Library.Util.nullpo(Util.java:40)
        at net.ME1312.SubServers.Sync.Event.SubCreateEvent.<init>(SubCreateEvent.java:38)
        at net.ME1312.SubServers.Sync.Network.Packet.PacketInExRunEvent$4.accept(PacketInExRunEvent.java:53)
        at net.ME1312.SubServers.Sync.Network.Packet.PacketInExRunEvent$4.accept(PacketInExRunEvent.java:49)
        at net.ME1312.SubServers.Sync.Network.Packet.PacketInExRunEvent.receive(PacketInExRunEvent.java:137)
        at net.ME1312.SubData.Client.Protocol.PacketObjectIn.receive(PacketObjectIn.java:32)
        at net.ME1312.SubData.Client.SubDataClient.lambda$read$6(SubDataClient.java:170)
        ... 3 more

### How It Happened
1. do creator.create(serverId, template, null, null)
2. Can create the server , but cannot connect the newly created server using SubServers.Sync

### Additional Information
None

**Comment by jingwenMC** [comment]
Updated the network to 22w24a,still.

**Comment by jingwenMC** [comment]
The port should be auto-assigned

**Comment by jingwenMC** [comment]
Also, the server list in command /server doesn't seem to be synchronized.

**Comment by ME1312** [comment]
This problem should be resolved as of the latest build. Give it a try.

**Comment by jingwenMC** [comment]
Still cannot sync the server list in /server command

**Comment by jingwenMC** [comment]
More exactly, cannot connect the new-created server, which created after SubServers.Sync loaded

**Comment by BasToTheMax** [comment]
Any updates?

**Comment by ME1312** [comment]
@BasToTheMax 
The issue that was originally identified no longer exists within SubServers as of the build mentioned above. As for the subsequently reported problems, I was unable to reproduce them.<br><br>

If you also have run into this type of problem, you can help me find it by:
1. Posting your SubServers application versions (`/sub version`),
2. Posting the specific code snippet you're using to generate and subsequently access the server info, and
3. Adding some debug code to it to help us identify which part of that, exactly, is failing.

**Comment by ME1312** [comment]
(Closing due to inactivity.)
