### ISSUE TITLE
ERROR: Cannot spoof chat on this client version!

### ISSUE THREAD

**Issue by LianJordaan** [ME1312/SubServers-2#88]
### Platform Information
14:34:57 [INFO] SubServers > These are the platforms and versions that are running SubServers.Bungee:
14:34:57 [INFO]   Linux 5.15.0-92-generic [x64],
14:34:57 [INFO]   Java 17.0.10 [x64],
14:34:57 [INFO]   BungeeCord git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:3e10075:1796,
14:34:57 [INFO]   SubServers.Bungee v2.18a (21w52a)
14:34:57 [INFO] 
14:34:57 [INFO] You are on the latest version.

### What Happened
I tried running any type of command from subserver in minecraft, but it gives a error in console, and does nothing in game..
14:25:55 [WARNING] Error in dispatching command
java.lang.UnsupportedOperationException: Cannot spoof chat on this client version!
    at net.md_5.bungee.UserConnection.chat(UserConnection.java:454)
    at net.ME1312.SubServers.Bungee.SubCommand.execute(SubCommand.java:673)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:208)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:158)
    at net.md_5.bungee.connection.UpstreamBridge.handleChat(UpstreamBridge.java:215)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:196)
    at net.md_5.bungee.protocol.packet.ClientCommand.handle(ClientCommand.java:109)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:840)

### How It Happened
i typed "/subservers" in minecraft

### Additional Information
I looked around everywhere i could, but could not find any info related to my problem..

**Comment by ME1312** [comment]
You can fix this by updating to a more modern (snapshot) build of SubServers.
